library(rJava)
library(RNetLogo)
setwd("C:/Program Files/NetLogo 6.0.3/app")
nl.path<-getwd()
NLStart("C:/Program Files/NetLogo 6.0.3/app", gui = TRUE, nl.jarname = "netlogo-6.0.3.jar")
model.path <- file.path("models", "Sample Models", "Earth Science", "Fire.nlogo")
NLLoadModel(model.path)
